/*
 * THIS FILE IS AUTOMATICALLY GENERATED BY gen_scrn_dispatch.pl
 * DO NOT EDIT!!
 */
#ifndef __glxlibglvnd_dispatchindex_h__
#define __glxlibglvnd_dispatchindex_h__

typedef enum __GLXdispatchIndex {
    DI_BindTexImageEXT,
    // ChooseFBConfig implemented by libglvnd
    DI_ChooseFBConfigSGIX,
    // ChooseVisual implemented by libglvnd
    // CopyContext implemented by libglvnd
    // CreateContext implemented by libglvnd
    DI_CreateContextAttribsARB,
    DI_CreateContextWithConfigSGIX,
    DI_CreateGLXPbufferSGIX,
    // CreateGLXPixmap implemented by libglvnd
    DI_CreateGLXPixmapWithConfigSGIX,
    // CreateNewContext implemented by libglvnd
    // CreatePbuffer implemented by libglvnd
    // CreatePixmap implemented by libglvnd
    // CreateWindow implemented by libglvnd
    // DestroyContext implemented by libglvnd
    DI_DestroyGLXPbufferSGIX,
    // DestroyGLXPixmap implemented by libglvnd
    // DestroyPbuffer implemented by libglvnd
    // DestroyPixmap implemented by libglvnd
    // DestroyWindow implemented by libglvnd
    // FreeContextEXT implemented by libglvnd
    // GetClientString implemented by libglvnd
    // GetConfig implemented by libglvnd
    DI_GetContextIDEXT,
    // GetCurrentContext implemented by libglvnd
    // GetCurrentDisplay implemented by libglvnd
    DI_GetCurrentDisplayEXT,
    // GetCurrentDrawable implemented by libglvnd
    // GetCurrentReadDrawable implemented by libglvnd
    // GetFBConfigAttrib implemented by libglvnd
    DI_GetFBConfigAttribSGIX,
    DI_GetFBConfigFromVisualSGIX,
    // GetFBConfigs implemented by libglvnd
    // GetProcAddress implemented by libglvnd
    // GetProcAddressARB implemented by libglvnd
    // GetSelectedEvent implemented by libglvnd
    DI_GetSelectedEventSGIX,
    DI_GetVideoSyncSGI,
    // GetVisualFromFBConfig implemented by libglvnd
    DI_GetVisualFromFBConfigSGIX,
    // ImportContextEXT implemented by libglvnd
    // IsDirect implemented by libglvnd
    // MakeContextCurrent implemented by libglvnd
    // MakeCurrent implemented by libglvnd
    // QueryContext implemented by libglvnd
    DI_QueryContextInfoEXT,
    // QueryDrawable implemented by libglvnd
    // QueryExtension implemented by libglvnd
    // QueryExtensionsString implemented by libglvnd
    DI_QueryGLXPbufferSGIX,
    // QueryServerString implemented by libglvnd
    // QueryVersion implemented by libglvnd
    DI_ReleaseTexImageEXT,
    // SelectEvent implemented by libglvnd
    DI_SelectEventSGIX,
    // SwapBuffers implemented by libglvnd
    DI_SwapIntervalSGI,
    // UseXFont implemented by libglvnd
    // WaitGL implemented by libglvnd
    DI_WaitVideoSyncSGI,
    // WaitX implemented by libglvnd
    DI_glXBindSwapBarrierSGIX,
    DI_glXCopySubBufferMESA,
    DI_glXCreateGLXPixmapMESA,
    DI_glXGetMscRateOML,
    DI_glXGetScreenDriver,
    DI_glXGetSwapIntervalMESA,
    DI_glXGetSyncValuesOML,
    DI_glXJoinSwapGroupSGIX,
    DI_glXQueryCurrentRendererIntegerMESA,
    DI_glXQueryCurrentRendererStringMESA,
    DI_glXQueryMaxSwapBarriersSGIX,
    DI_glXQueryRendererIntegerMESA,
    DI_glXQueryRendererStringMESA,
    DI_glXReleaseBuffersMESA,
    DI_glXSwapBuffersMscOML,
    DI_glXSwapIntervalMESA,
    DI_glXWaitForMscOML,
    DI_glXWaitForSbcOML,
    DI_LAST_INDEX
} __GLXdispatchIndex;

#endif // __glxlibglvnd_dispatchindex_h__
