ISL_FILES = \
	isl.c \
	isl.h \
	isl_format.c \
	isl_format_layout.c \
	isl_gen4.c \
	isl_gen4.h \
	isl_gen6.c \
	isl_gen6.h \
	isl_storage_image.c

ISL_GEN7_FILES = \
	isl_gen7.c \
	isl_gen7.h \
	isl_surface_state.c

ISL_GEN75_FILES = \
	isl_surface_state.c

ISL_GEN8_FILES = \
	isl_gen8.c \
	isl_gen8.h \
	isl_surface_state.c

ISL_GEN9_FILES = \
	isl_gen9.c \
	isl_gen9.h \
	isl_surface_state.c

ISL_GENERATED_FILES = \
	isl_format_layout.c
