MESA_UTIL_FILES :=	\
	bitset.h \
	debug.c \
	debug.h \
	format_srgb.h \
	hash_table.c	\
	hash_table.h \
	list.h \
	macros.h \
	mesa-sha1.c \
	mesa-sha1.h \
	ralloc.c \
	ralloc.h \
	register_allocate.c \
	register_allocate.h \
	rgtc.c \
	rgtc.h \
	rounding.h \
	set.c \
	set.h \
	simple_list.h \
	strndup.c \
	strndup.h \
	strtod.c \
	strtod.h \
	texcompress_rgtc_tmp.h \
	u_atomic.h

MESA_UTIL_GENERATED_FILES = \
	format_srgb.c
