DDEBUG_SOURCES := \
	$(top_srcdir)/src/gallium/drivers/ddebug/dd_context.c \
	$(top_srcdir)/src/gallium/drivers/ddebug/dd_draw.c \
	$(top_srcdir)/src/gallium/drivers/ddebug/dd_pipe.h \
	$(top_srcdir)/src/gallium/drivers/ddebug/dd_public.h \
	$(top_srcdir)/src/gallium/drivers/ddebug/dd_screen.c \
	$(top_srcdir)/src/gallium/drivers/ddebug/dd_util.h
