TRACE_SOURCES := \
	$(top_srcdir)/src/gallium/drivers/trace/tr_context.c \
	$(top_srcdir)/src/gallium/drivers/trace/tr_context.h \
	$(top_srcdir)/src/gallium/drivers/trace/tr_dump.c \
	$(top_srcdir)/src/gallium/drivers/trace/tr_dump_defines.h \
	$(top_srcdir)/src/gallium/drivers/trace/tr_dump.h \
	$(top_srcdir)/src/gallium/drivers/trace/tr_dump_state.c \
	$(top_srcdir)/src/gallium/drivers/trace/tr_dump_state.h \
	$(top_srcdir)/src/gallium/drivers/trace/tr_public.h \
	$(top_srcdir)/src/gallium/drivers/trace/tr_screen.c \
	$(top_srcdir)/src/gallium/drivers/trace/tr_screen.h \
	$(top_srcdir)/src/gallium/drivers/trace/tr_texture.c \
	$(top_srcdir)/src/gallium/drivers/trace/tr_texture.h
