#!/bin/sh
set -eu

LIB=${1-.libs/libwayland-egl.so}

if ! [ -f "$LIB" ]
then
  exit 1
fi

FUNCS=$($NM -D --defined-only $LIB | grep -o "T .*" | cut -c 3- | while read func; do
( grep -q "^$func$" || echo $func )  <<EOF
wl_egl_window_resize
wl_egl_window_create
wl_egl_window_destroy
wl_egl_window_get_attached_size
_fini
_init
EOF
done)

test ! -n "$FUNCS" || echo $FUNCS
test ! -n "$FUNCS"

