gpir_SOURCES := \
	  ir/gp/gpir.h \
	  ir/gp/nir.h \
	  ir/gp/nir.c \
	  ir/gp/node.c \
	  ir/gp/lower.c \
	  ir/gp/scheduler.c \
	  ir/gp/instr.c \
	  ir/gp/codegen.h \
	  ir/gp/codegen.c

C_SOURCES := \
	  lima_screen.c \
	  lima_screen.h \
	  lima_context.c \
	  lima_context.h \
	  lima_resource.c \
	  lima_resource.h \
	  lima_state.c \
	  lima_draw.c \
	  lima_program.c \
	  $(gpir_SOURCES)
