// DriConf options specific to radeonsi
DRI_CONF_SECTION_PERFORMANCE
    DRI_CONF_RADEONSI_ENABLE_SISCHED("false")
    DRI_CONF_RADEONSI_ASSUME_NO_Z_FIGHTS("false")
    DRI_CONF_RADEONSI_COMMUTATIVE_BLEND_ADD("false")
DRI_CONF_SECTION_END
