C_SOURCES := \
	cik_sdma.c \
	si_blit.c \
	si_compute.c \
	si_cp_dma.c \
	si_debug.c \
	si_descriptors.c \
	sid.h \
	si_dma.c \
	si_hw_context.c \
	si_pipe.c \
	si_pipe.h \
	si_pm4.c \
	si_pm4.h \
	si_perfcounter.c \
	si_public.h \
	si_shader.c \
	si_shader.h \
	si_state.c \
	si_state_draw.c \
	si_state_shaders.c \
	si_state.h \
	si_uvd.c

GENERATED_SOURCES := \
	sid_tables.h
