RBUG_SOURCES := \
	$(top_srcdir)/src/gallium/drivers/rbug/rbug_context.c \
	$(top_srcdir)/src/gallium/drivers/rbug/rbug_context.h \
	$(top_srcdir)/src/gallium/drivers/rbug/rbug_core.c \
	$(top_srcdir)/src/gallium/drivers/rbug/rbug_objects.c \
	$(top_srcdir)/src/gallium/drivers/rbug/rbug_objects.h \
	$(top_srcdir)/src/gallium/drivers/rbug/rbug_public.h \
	$(top_srcdir)/src/gallium/drivers/rbug/rbug_screen.c \
	$(top_srcdir)/src/gallium/drivers/rbug/rbug_screen.h
